# torch.nn.functional

## Convolution 函数
### torch.nn.functional.conv1d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)

对几个输入平面组成的输入信号应用1D（一维）卷积。 有关详细信息和输出形状，请参见 Conv1d 。

参数： 
- input – 输入张量的形状 (minibatch x in_channels x iW) 
- weight – 过滤器的形状 (out_channels, in_channels, kW) 
- bias – 可选偏置的形状 (out_channels) 
- stride – 卷积核的步长，默认为1

In [1]:
import torch
from torch import autograd
import torch.nn.functional as F

In [2]:
filters = autograd.Variable(torch.randn(33, 16, 3))
inputs = autograd.Variable(torch.randn(20, 16, 50))
F.conv1d(inputs, filters)

tensor([[[ 4.0910e+00,  1.2746e+00,  1.3093e+01,  ..., -5.6192e+00,
           1.5224e+00,  5.8159e+00],
         [ 1.2228e+01,  1.1855e+01,  4.6436e+00,  ...,  3.2987e+00,
           5.8506e+00,  4.1566e+00],
         [-1.7404e+00, -5.3658e+00,  2.6954e+00,  ..., -3.3302e-01,
           6.2116e+00,  4.6132e+00],
         ...,
         [-8.7469e+00,  8.6097e+00, -4.1213e+00,  ...,  9.0458e-02,
          -1.2159e+01, -7.5299e+00],
         [ 5.8603e+00, -5.6252e+00,  3.2814e+00,  ..., -5.6246e-01,
           2.9551e+00,  1.8501e+01],
         [-8.9731e+00, -7.8859e-01,  1.1931e+01,  ...,  2.7926e+00,
           8.3333e-01, -1.4514e+01]],

        [[ 4.8804e+00,  6.8274e+00,  1.3089e+00,  ...,  7.3061e+00,
          -1.9042e+00, -2.7113e+00],
         [ 5.0816e+00,  2.1482e+00, -1.1752e+01,  ..., -1.7421e+00,
           1.0823e+00,  1.0024e+01],
         [-1.5022e+01, -6.0568e-01,  3.2907e+00,  ..., -7.0923e-01,
          -2.2644e+00,  2.5486e+00],
         ...,
         [-5.0079e-01, -1

### torch.nn.functional.conv2d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)

对几个输入平面组成的输入信号应用2D卷积。 有关详细信息和输出形状，请参见 Conv2d 。

参数：
- input – 输入张量 (minibatch x in_channels x iH x iW) 
- weight – 过滤器张量 (out_channels, in_channels/groups, kH, kW) 
- bias – 可选偏置张量 (out_channels) 
- stride – 卷积核的步长，可以是单个数字或一个元组 (sh x sw)。默认为1 
- padding – 输入上隐含零填充。 可以是单个数字或元组。 默认值：0 
- groups – 将输入分成组，in_channels应该被组数除尽

In [3]:
# With square kernels and equal stride
filters = autograd.Variable(torch.randn(8,4,3,3))
inputs = autograd.Variable(torch.randn(1,4,5,5))
F.conv2d(inputs, filters, padding=1)

tensor([[[[-5.4119e-02,  3.3753e+00,  6.7146e-01, -8.5523e+00,  6.5412e+00],
          [ 3.7080e-01, -3.1662e+00, -5.3672e-01,  7.3597e+00,  8.3691e+00],
          [-1.4331e+00, -5.8819e-01,  1.0410e+01,  5.3745e+00, -2.4462e+00],
          [-1.2571e+01,  1.3455e-02, -4.1606e+00, -4.6117e+00,  4.9175e+00],
          [-8.2907e+00, -2.0928e+00, -6.8445e+00,  5.8670e+00,  2.2476e+00]],

         [[-1.1513e+00,  5.1455e+00,  1.5351e+00, -1.4796e+00, -2.0224e+00],
          [-5.6302e+00, -5.5882e+00,  8.6554e+00, -3.3394e+00,  2.3090e+00],
          [ 1.8197e+00,  1.2870e+00, -4.3271e-01, -1.8481e+00,  1.1259e+00],
          [-9.5713e+00,  3.3243e+00, -1.4797e+00,  2.5831e+00,  3.3286e+00],
          [ 1.7168e+00, -7.4784e+00,  3.5701e+00, -1.9641e+00, -3.3731e+00]],

         [[-5.2279e-01, -4.6187e+00, -8.7876e-01,  1.6635e+00, -2.1674e+00],
          [ 2.9052e+00,  1.5868e+00,  6.4764e+00,  8.5155e+00, -1.5919e+01],
          [ 3.1077e+00,  1.1326e+01, -2.9387e+00, -1.0763e+01, -3.4723e+

### torch.nn.functional.conv3d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)

对几个输入平面组成的输入信号应用3D卷积。 有关详细信息和输出形状，请参见 Conv3d 。

参数： 
- input – 输入张量的形状 (minibatch x in_channels x iT x iH x iW) 
- weight – 过滤器张量 的形状 (out_channels, in_channels, kT, kH, kW) 
- bias – 可选偏置张量的形状 (out_channels) 
- stride – 卷积核的步长，可以是单个数字或一个元组 (sh x sw)。默认为1 
- padding – 输入上隐 含零填充。可以是单个数字或元组。 默认值：0

In [4]:
filters = autograd.Variable(torch.randn(33, 16, 3, 3, 3))
inputs = autograd.Variable(torch.randn(20, 16, 50, 10, 20))
F.conv3d(inputs, filters)

tensor([[[[[ 4.1161e+01, -1.0434e+01, -1.2643e+01,  ..., -1.6542e+01,
            -1.4606e+01,  1.4156e+01],
           [ 4.9931e+00, -2.2831e+01, -1.2825e+01,  ..., -6.7927e+00,
             1.1988e+01,  1.5875e+01],
           [-3.2071e+01,  5.2264e+00, -1.1677e+01,  ...,  1.0813e+01,
             2.7621e+00,  1.1468e+01],
           ...,
           [-4.5656e+01, -5.4573e+00,  1.5794e+01,  ..., -1.7488e+01,
             4.1186e+01, -3.8321e+01],
           [ 2.6206e+00,  7.7757e+00, -2.3285e+01,  ..., -5.1505e+00,
             3.0232e+00, -1.4973e+00],
           [ 1.6142e+01, -1.0456e+01, -2.8018e+01,  ...,  3.8569e+01,
            -5.4558e+00,  1.4217e+01]],

          [[ 3.4312e+01,  4.3441e+00, -9.3609e+00,  ...,  9.3957e+00,
             1.5157e+00,  4.4296e+01],
           [ 1.4458e+01,  3.1759e+00,  1.5342e+01,  ..., -1.6613e+01,
            -3.1984e+01,  9.5534e+00],
           [-2.5717e+01, -2.6193e+01,  6.0278e+00,  ..., -2.4641e+01,
             4.0979e+00,  1.0392e+00],
 

### torch.nn.functional.conv_transpose1d(input, weight, bias=None, stride=1, padding=0, output_padding=0)
### torch.nn.functional.conv_transpose2d(input, weight, bias=None, stride=1, padding=0, output_padding=0)

在由几个输入平面组成的输入图像上应用二维转置卷积，有时也称为“去卷积”。 有关详细信息和输出形状，请参阅 ConvTranspose2d 。

参数： 
- input – 输入张量的形状 (minibatch x in_channels x iH x iW) 
- weight – 过滤器的形状 (in_channels x out_channels x kH x kW) 
- bias – 可选偏置的形状 (out_channels) 
- stride – 卷积 核的步长，可以是单个数字或一个元组 (sh x sw)。默认: 1 
- padding – 输入上隐含零填充。可 以是单个数字或元组。 (padh x padw)。默认: 0 
- groups – 将输入分成组， in_channels 应该被 组数除尽 
- output_padding – 0 <= padding <stride的零填充，应该添加到输出。可以是单个数 字或元组。默认值：0