In [1]:
import torch
import numpy

# 张量Tensors

### torch.numel
torch.numel(input)->int  
返回input张量中的元素个数

In [2]:
a = torch.randn(1,2,3,4,5)
torch.numel(a)

120

In [3]:
a = torch.zeros(4, 4)
torch.numel(a)

16

# 创建操作 Creation Ops

### torch.eye
torch.eye(n, m=None, out=None)  
返回一个2维张量，对角线位置全1，其它位置全0

In [4]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### from_numpy
torch.from_numpy(ndarray) → Tensor  
Numpy桥，将numpy.ndarray转换为pytorch的Tensor。返回的张量tensor和numpy的ndarray共享同一内存空间。修改一个会导致另外一个也被修改。返回的张量不能改变大小。

In [5]:
a = numpy.array([1, 2, 3])
t = torch.from_numpy(a)
t

tensor([1, 2, 3], dtype=torch.int32)

In [6]:
t[0] = -1
a

array([-1,  2,  3])

### torch.linspace
torch.linspace(start, end, steps=100, out=None) → Tensor  
返回一个1维张量，包含在区间start和end上均匀间隔的steps个点。 输出1维张量的长度为steps。

In [7]:
torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [8]:
torch.linspace(-10, 10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

In [9]:
torch.linspace(start=-1, end=10, steps=5)

tensor([-1.0000,  1.7500,  4.5000,  7.2500, 10.0000])

### torch.logspace
torch.logspace(start, end, steps=100, out=None) → Tensor  
返回一个1维张量，包含在区间$10^{start}$和$10^{end}$上以对数刻度均匀间隔的steps个点。 输出1维张量的长度为steps。

In [10]:
torch.logspace(start=-10, end=10, steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [11]:
torch.logspace(start=0.1, end=1.0, steps=5)

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

### torch.ones
torch.ones(*sizes, out=None) → Tensor  
返回一个全为1 的张量，形状由可变参数sizes定义。

In [12]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

### torch.rand
torch.rand(*sizes, out=None) → Tensor  
返回一个张量，包含了从区间[0,1)的均匀分布中抽取的一组随机数，形状由可变参数sizes定义。

In [14]:
torch.rand(4)

tensor([0.7631, 0.4207, 0.7791, 0.5156])

In [15]:
torch.rand(2, 3)

tensor([[0.5023, 0.2066, 0.9565],
        [0.1090, 0.4066, 0.8132]])

### torch.randn
torch.randn(*sizes, out=None) → Tensor  
返回一个张量，包含了从标准正态分布(均值为0，方差为1，即高斯白噪声)中抽取一组随机数，形状由可变参数sizes定义。 

In [16]:
torch.randn(4)

tensor([ 1.2805, -1.5038, -0.4385, -1.7496])

In [17]:
torch.randn(2, 3)

tensor([[ 0.6824, -0.4872,  0.1874],
        [-0.8315, -0.5345,  0.7241]])

### torch.randperm
torch.randperm(n, out=None) → LongTensor  
给定参数n ，返回一个从0到n-1的随机整数排列。

In [18]:
torch.randperm(4)

tensor([2, 0, 3, 1])

### torch.arange
torch.arange(start, end, step=1, out=None) → Tensor  
返回一个1维张量，长度为$floor((end-start)/step)$。包含从start到end ，以step为步长的一组序列值(默认步长为1)

In [19]:
torch.arange(1, 4)

tensor([1, 2, 3])

In [20]:
torch.arange(1, 2.5, 0.5)

tensor([1.0000, 1.5000, 2.0000])

### torch.zeros
torch.zeros(*sizes, out=None) → Tensor  
返回一个全为标量0的张量，形状由可变参数sizes定义。

In [21]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

# 索引/切片/连接/换位 Indexing, Slicing, Joining, Mutating Ops

### torch.cat
torch.cat(inputs, dimension=0) → Tensor  
在给定维度上对输入的张量序列 seq 进行连接操作。  
torch.cat() 可以看做 torch.split() 和 torch.chunk() 的反操作。cat() 函数可以通过下面例子更好的理解。

In [23]:
x = torch.randn(2, 3)
x

tensor([[-0.3095,  0.7501,  0.9793],
        [-0.1466, -1.6512, -0.4246]])

In [24]:
torch.cat((x, x, x), 0)

tensor([[-0.3095,  0.7501,  0.9793],
        [-0.1466, -1.6512, -0.4246],
        [-0.3095,  0.7501,  0.9793],
        [-0.1466, -1.6512, -0.4246],
        [-0.3095,  0.7501,  0.9793],
        [-0.1466, -1.6512, -0.4246]])

In [25]:
torch.cat((x, x, x), 1)

tensor([[-0.3095,  0.7501,  0.9793, -0.3095,  0.7501,  0.9793, -0.3095,  0.7501,
          0.9793],
        [-0.1466, -1.6512, -0.4246, -0.1466, -1.6512, -0.4246, -0.1466, -1.6512,
         -0.4246]])