In [1]:
import torch

# 比较操作 Comparison Ops

### torch.ge
torch.ge(input, other, out=None) → Tensor  
逐元素比较 input 和 other，即是否$input \geqslant other$。  
如果两个张量有相同的形状和元素值，则返回 True ，否则 False 。 第二个参数可以为一个数或与第一个参数相同形状和类型的张量

In [2]:
torch.ge(torch.Tensor([[1, 2], [3, 4]]), torch.Tensor([[1, 1], [4, 4]]))

tensor([[1, 1],
        [0, 1]], dtype=torch.uint8)

### torch.gt
torch.gt(input, other, out=None) → Tensor  
逐元素比较 input 和 other ， 即是否 如果两个张量有相同的形状和元素值，则返回 True ，否则 False 。 第二个参数可以为一个数或与第一个参数相同形状和类型的张量

In [3]:
torch.gt(torch.Tensor([[1, 2], [3, 4]]), torch.Tensor([[1, 1], [4, 4]]))

tensor([[0, 1],
        [0, 0]], dtype=torch.uint8)

### torch.kthvalue
torch.kthvalue(input, k, dim=None, out=None) -> (Tensor, LongTensor)  
取输入张量 input 指定维上第k 个最小值。如果不指定 dim ，则默认为 input 的最后一维。
返回一个元组 (values,indices)，其中 indices 是原始输入张量 input 中沿 dim 维的第 k 个最小值下标。

In [4]:
x = torch.arange(1, 6)
x

tensor([1, 2, 3, 4, 5])

In [5]:
# 取第k个最小值
torch.kthvalue(x, 4)

torch.return_types.kthvalue(
values=tensor(4),
indices=tensor(3))

### torch.le
torch.le(input, other, out=None) → Tensor  
逐元素比较 input 和 other ， 即是否$input \leqslant other$第二个参数可以为一个数或与第一个参数相同形状和类型的张量

In [6]:
torch.le(torch.Tensor([[1, 2], [3, 4]]), torch.Tensor([[1, 1], [4, 4]]))

tensor([[1, 0],
        [1, 1]], dtype=torch.uint8)

### torch.lt
torch.lt(input, other, out=None) → Tensor  
逐元素比较 input 和 other ， 即是否$input < other$  
第二个参数可以为一个数或与第一个参数相同形状和类型的张量

In [7]:
torch.lt(torch.Tensor([[1, 2], [3, 4]]), torch.Tensor([[1, 1], [4, 4]]))

tensor([[0, 0],
        [1, 0]], dtype=torch.uint8)

### torch.max
torch.max()  
返回输入张量所有元素的最大值。

In [8]:
a = torch.randn(1, 3)
a

tensor([[ 1.2990, -0.2886, -0.1625]])

In [9]:
torch.max(a)

tensor(1.2990)

torch.max(input, dim, max=None, max_indices=None) -> (Tensor, LongTensor)  
返回输入张量给定维度上每行的最大值，并同时返回每个最大值的位置索引。  
输出形状中，将 dim 维设定为1，其它与输入形状保持一致。

In [10]:
a = torch.randn(4, 4)
a

tensor([[-0.0287, -0.3009,  1.1667, -1.0525],
        [-0.3748,  0.1419,  1.6414,  0.0937],
        [ 0.4776, -0.1963, -1.9010,  0.0935],
        [ 0.6471, -0.8917,  0.3899, -0.3949]])

In [11]:
# 按行取最大值
torch.max(a, 1)

torch.return_types.max(
values=tensor([1.1667, 1.6414, 0.4776, 0.6471]),
indices=tensor([2, 2, 0, 0]))

torch.max(input, other, out=None) → Tensor  
返回输入张量给定维度上每行的最大值，并同时返回每个最大值的位置索引。 即$out_i=max(input_i, other_i)$  
输出形状中，将 dim 维设定为1，其它与输入形状保持一致。

In [12]:
a = torch.randn(4)
a

tensor([ 0.2908, -0.9157,  0.9614,  0.3274])

In [13]:
b = torch.randn(4)
b

tensor([-0.8886, -0.4459,  0.4276, -0.3026])

In [14]:
torch.max(a, b)

tensor([ 0.2908, -0.4459,  0.9614,  0.3274])

### torch.min
torch.min(input) → float  
返回输入张量所有元素的最小值。

In [15]:
a = torch.randn(1, 3)
a

tensor([[-2.1048, -1.0820,  0.3809]])

In [16]:
torch.min(a)

tensor(-2.1048)

torch.min(input, dim, min=None, min_indices=None) -> (Tensor, LongTensor)  
返回输入张量给定维度上每行的最小值，并同时返回每个最小值的位置索引。  
输出形状中，将 dim 维设定为1，其它与输入形状保持一致。

In [17]:
a = torch.randn(4, 4)
a

tensor([[-1.3044,  1.5756,  1.4488,  1.6483],
        [-2.9373, -0.5015, -1.9494,  1.2411],
        [-1.2833, -1.0122, -1.4623, -1.1097],
        [-0.4786, -0.4191,  0.8416, -0.3656]])

In [18]:
torch.min(a, 1)

torch.return_types.min(
values=tensor([-1.3044, -2.9373, -1.4623, -0.4786]),
indices=tensor([0, 0, 2, 0]))

torch.min(input, other, out=None) → Tensor  
input 中逐元素与 other 相应位置的元素对比，返回最小值到输出张量。即$out_i=min(tensor_i, other_i)$  
两张量形状不需匹配，但元素数须相同。  
注意：当形状不匹配时， input 的形状作为返回张量的形状。

In [19]:
a = torch.randn(4)
a

tensor([ 0.2847, -0.9817, -0.5501, -0.2095])

In [20]:
b = torch.randn(4)
b

tensor([ 1.7007, -0.0122, -0.1574,  0.3346])

In [21]:
torch.min(a, b)

tensor([ 0.2847, -0.9817, -0.5501, -0.2095])

### torch.ne
torch.ne(input, other, out=None) → Tensor  
逐元素比较 input 和 other，即是否$input != other$。第二个参数可以为一个数或与第一个参数相同形状和类型的张量

In [22]:
torch.ne(torch.Tensor([[1, 2], [3, 4]]), torch.Tensor([[1, 1], [4, 4]]))

tensor([[0, 1],
        [1, 0]], dtype=torch.uint8)

### torch.sort
torch.sort(input, dim=None, descending=False, out=None) -> (Tensor, LongTensor)  
对输入张量 input 沿着指定维按升序排序。如果不给定 dim ，则默认为输入的最后一维。如果指定参数 descending 为 True ，则按降序排序  
返回元组 (sorted_tensor, sorted_indices) ， sorted_indices 为原始输入中的下标。

In [23]:
x = torch.randn(3, 4)
sorted, indices = torch.sort(x)
sorted

tensor([[-0.0274,  0.3800,  0.3961,  1.3038],
        [-0.5760, -0.4788,  0.0229,  0.4699],
        [-0.5173, -0.3512, -0.2068,  1.6947]])

In [24]:
indices

tensor([[1, 0, 3, 2],
        [2, 0, 3, 1],
        [1, 2, 0, 3]])

In [25]:
sorted, indices = torch.sort(x, 0)
sorted

tensor([[-0.4788, -0.5173, -0.5760,  0.0229],
        [-0.2068, -0.0274, -0.3512,  0.3961],
        [ 0.3800,  0.4699,  1.3038,  1.6947]])

In [26]:
indices

tensor([[1, 2, 1, 1],
        [2, 0, 2, 0],
        [0, 1, 0, 2]])

### torch.topk
torch.topk(input, k, dim=None, largest=True, sorted=True, out=None) -> (Tensor, LongTensor)  
沿给定 dim 维度返回输入张量 input 中 k 个最大值。 如果不指定 dim ，则默认为 input 的最后一维。如果为 largest 为 False ，则返回最小的 k 个值。  
返回一个元组 (values,indices)，其中 indices 是原始输入张量 input 中测元素下标。如果设定布尔值 sorted 为_True_，将会确保返回的 k 个值被排序。

In [27]:
x = torch.arange(1, 6)
x

tensor([1, 2, 3, 4, 5])

In [28]:
torch.topk(x, 3)

torch.return_types.topk(
values=tensor([5, 4, 3]),
indices=tensor([4, 3, 2]))

In [29]:
torch.topk(x, 3, largest=False)

torch.return_types.topk(
values=tensor([1, 2, 3]),
indices=tensor([0, 1, 2]))

# 其它操作 Other Operations

### torch.cross
torch.cross(input, other, dim=-1, out=None) → Tensor  
返回沿着维度 dim 上，两个张量 input 和 other 的向量积（叉积）。 input 和 other 必须有相同的形状，且指定的 dim 维上size必须为 3。  
如果不指定 dim ，则默认为第一个尺度为 3 的维。

In [30]:
a = torch.randn(4, 3)
a

tensor([[-0.5804,  0.3432, -0.2196],
        [ 0.3225,  0.2474, -1.6775],
        [ 1.1070, -1.0603,  2.0992],
        [ 0.5278,  1.4472, -0.6604]])

In [31]:
b = torch.randn(4, 3)
b

tensor([[-0.1671, -0.3354, -1.2149],
        [-0.0036, -1.1630,  1.0006],
        [-0.5885, -1.3894, -1.4368],
        [ 0.2904, -0.2142,  0.4272]])

In [32]:
torch.cross(a, b, dim=1)

tensor([[-0.4906, -0.6685,  0.2520],
        [-1.7033, -0.3166, -0.3742],
        [ 4.4402,  0.3552, -2.1621],
        [ 0.4768, -0.4173, -0.5333]])

In [33]:
torch.cross(a, b)

tensor([[-0.4906, -0.6685,  0.2520],
        [-1.7033, -0.3166, -0.3742],
        [ 4.4402,  0.3552, -2.1621],
        [ 0.4768, -0.4173, -0.5333]])

### torch.diag
torch.diag(input, diagonal=0, out=None) → Tensor  
如果输入是一个向量(1D 张量)，则返回一个以 input 为对角线元素的2D方阵  
如果输入是一个矩阵(2D 张量)，则返回一个包含 input 对角线元素的1D张量

**取得以 input 为对角线的方阵：**

In [34]:
a = torch.randn(3)
a

tensor([-0.8659, -0.6496,  1.1525])

In [35]:
torch.diag(a)

tensor([[-0.8659,  0.0000,  0.0000],
        [ 0.0000, -0.6496,  0.0000],
        [ 0.0000,  0.0000,  1.1525]])

In [36]:
torch.diag(a, 1)

tensor([[ 0.0000, -0.8659,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.6496,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  1.1525],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

**取得给定矩阵第 k 个对角线：**

In [37]:
a = torch.randn(3, 3)
a

tensor([[-0.9067,  0.5443,  0.9428],
        [-0.8577,  0.0506, -1.2518],
        [-1.2374,  0.0361, -0.3659]])

In [38]:
torch.diag(a, 0)

tensor([-0.9067,  0.0506, -0.3659])

In [39]:
torch.diag(a, 1)

tensor([ 0.5443, -1.2518])

### torch.histc
torch.histc(input, bins=100, min=0, max=0, out=None) → Tensor  
计算输入张量的直方图。以 min 和 max 为range边界，将其均分成 bins 个直条，然后将排序好的数据划分到各个直条(bins)中。如果 min 和 max 都为0, 则利用数据中的最大最小值作为边界。

In [40]:
torch.histc(torch.FloatTensor([1, 2, 1]), bins=4, min=0, max=3)

tensor([0., 2., 1., 0.])

### torch.renorm
torch.renorm(input, p, dim, maxnorm, out=None) → Tensor  
返回一个张量，包含规范化后的各个子张量，使得沿着dim维划分的各子张量的p范数小于maxnorm。  
**注意：** 如果p范数的值小于 maxnorm ，则当前子张量不需要修改。

In [41]:
x = torch.ones(3, 3)
x[1].fill_(2)
x[2].fill_(3)
x

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [42]:
torch.renorm(x, 1, 0, 5)

tensor([[1.0000, 1.0000, 1.0000],
        [1.6667, 1.6667, 1.6667],
        [1.6667, 1.6667, 1.6667]])

### torch.trace
torch.trace(input) → float  
返回输入2维矩阵对角线元素的和(迹)

In [43]:
x = torch.arange(1, 10).view(3, 3)
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
torch.trace(x)

tensor(15)

### torch.tril
torch.tril(input, diagonal=0, out=None) → Tensor  
返回一个张量 out ，包含输入矩阵(2D张量)的下三角部分， out 其余部分被设为 0 。这里所说的下三角部分为矩阵指定对角线 diagonal 之上的元素。

In [45]:
a = torch.randn(3, 3)
a

tensor([[-0.2376, -0.2659, -1.0257],
        [-0.8349, -0.0022,  0.0860],
        [-0.6707, -0.9868,  0.7312]])

In [46]:
torch.tril(a)

tensor([[-0.2376,  0.0000,  0.0000],
        [-0.8349, -0.0022,  0.0000],
        [-0.6707, -0.9868,  0.7312]])

In [47]:
torch.tril(a, diagonal=1)

tensor([[-0.2376, -0.2659,  0.0000],
        [-0.8349, -0.0022,  0.0860],
        [-0.6707, -0.9868,  0.7312]])

In [48]:
torch.tril(a, diagonal=-1)

tensor([[ 0.0000,  0.0000,  0.0000],
        [-0.8349,  0.0000,  0.0000],
        [-0.6707, -0.9868,  0.0000]])

### torch.triu
triu(input, diagonal=0, out=None) → Tensor  
返回一个张量，包含输入矩阵(2D张量)的上三角部分，其余部分被设为 0 。这里所说的上三角部分为矩阵指定对角线 diagonal 之上的元素。

In [49]:
a = torch.randn(3, 3)
a

tensor([[-0.2944, -2.0081, -1.5021],
        [ 0.0852, -0.5450, -0.1627],
        [-0.1629,  0.6683,  0.3073]])

In [50]:
torch.triu(a)

tensor([[-0.2944, -2.0081, -1.5021],
        [ 0.0000, -0.5450, -0.1627],
        [ 0.0000,  0.0000,  0.3073]])

In [51]:
torch.triu(a, diagonal=1)

tensor([[ 0.0000, -2.0081, -1.5021],
        [ 0.0000,  0.0000, -0.1627],
        [ 0.0000,  0.0000,  0.0000]])

In [52]:
torch.triu(a, diagonal=-1)

tensor([[-0.2944, -2.0081, -1.5021],
        [ 0.0852, -0.5450, -0.1627],
        [ 0.0000,  0.6683,  0.3073]])

# BLAS and LAPACK Operations

### torch.addbmm
torch.addbmm(beta=1, mat, alpha=1, batch1, batch2, out=None) → Tensor  
对两个批 batch1 和 batch2 内存储的矩阵进行批矩阵乘操作，附带reduced add 步骤( 所有矩阵乘结果沿着第一维相加)。矩阵 mat 加到最终结果。 batch1 和 batch2 都为包含相同数量矩阵的3维张量。 如果 batch1 是形为$b \times n \times m$的张量， batch1 是形为$b \times m \times p$的张量，则out 和 mat 的形状都是$n \times p$ ，即$res = (beta*M) + (alpha * sum( batch1_i \mathbin{@} batch2_i,i=0,b))$  
对类型为 FloatTensor 或 DoubleTensor 的输入， alpha and beta 必须为实数，否则两个参数
须为整数。

In [53]:
M = torch.randn(3, 5)
batch1 = torch.randn(10, 3 ,4)
batch2 = torch.randn(10, 4, 5)
torch.addbmm(M, batch1, batch2)

tensor([[ -0.3218,  -0.1129,  10.1543,   4.6413,  -1.3953],
        [  0.7677, -10.6244,  -1.6786, -14.7861,   5.1038],
        [ -4.9798,  -2.1606,  -4.7059,  -0.2605,   9.6562]])

### torch.addmm
torch.addmm(beta=1, mat, alpha=1, mat1, mat2, out=None) → Tensor  
对矩阵 mat1 和 mat2 进行矩阵乘操作。矩阵 mat 加到最终结果。如果 mat1 是一个$n \times m$ 张量，mat2 是一个$m \times p$张量，那么 out 和 mat 的形状为$n \times p$ 。 alpha 和 beta 分别是两个矩阵$mat1 \mathbin{@} mat2$和$mat$的比例因子，即$ out=(beta*M) + (alpha*mat1\mathbin{@}mat2) $  
对类型为 FloatTensor 或 DoubleTensor 的输入， beta and alpha 必须为实数，否则两个参数须为整数。

In [54]:
M = torch.randn(2, 3)
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.addmm(M, mat1, mat2)

tensor([[-0.8045, -0.8936,  1.1515],
        [ 0.7857,  2.1823, -1.0061]])

### torch.addmv
torch.addmv(beta=1, tensor, alpha=1, mat, vec, out=None) → Tensor  
对矩阵 mat 和向量 vec 对进行相乘操作。向量 tensor 加到最终结果。如果 mat 是一个$n \times m$维矩阵， vec 是一个 维向量，那么 out 和 mat 的为$n$元向量。 可选参数_alpha_ 和beta 分别是$mat*vec$和$mat$的比例因子，即$out = (beta ∗ tensor) + (alpha ∗ (mat@vec))$  
对类型为_FloatTensor_或_DoubleTensor_的输入， alpha and beta 必须为实数，否则两个参数须为整数。

In [55]:
M = torch.randn(2)
mat = torch.randn(2, 3)
vec = torch.randn(3)
torch.addmv(M, mat, vec)

tensor([-0.3892,  3.1394])

### torch.addr
torch.addr(beta=1, mat, alpha=1, vec1, vec2, out=None) → Tensor  
对向量 vec1 和 vec2 对进行张量积操作。矩阵 mat 加到最终结果。如果 vec1 是一个$n$维向量， vec2 是一个$m$维向量，那么矩阵 mat 的形状须为$n \times m$。可选参数_beta_ 和 alpha 分别是两个矩阵$mat$和$vec1@vec2$的比例因子，即$resi=(beta*M_i)+(alpha*batch1_i \times batch2_i)$  
对类型为_FloatTensor_或_DoubleTensor_的输入， alpha and beta 必须为实数，否则两个参数须为整数。

In [56]:
vec1 = torch.arange(1., 4.)
vec2 = torch.arange(1., 3.)
M = torch.zeros(3, 2)
torch.addr(M, vec1, vec2)

tensor([[1., 2.],
        [2., 4.],
        [3., 6.]])

### torch.baddbmm
torch.baddbmm(beta=1, mat, alpha=1, batch1, batch2, out=None) → Tensor 
对两个批 batch1 和 batch2 内存储的矩阵进行批矩阵乘操作，矩阵 mat 加到最终结果。
batch1 和 batch2 都为包含相同数量矩阵的3维张量。 如果 batch1 是形为$b \times n \times m$ 的张量， batch1 是形为$b \times m \times p$的张量，则 out 和 mat 的形状都是$n \times p$ ，即$resi=(beta*M_i)+(alpha*batch1_i \times batch2_i)$  
对类型为_FloatTensor_或_DoubleTensor_的输入， alpha and beta 必须为实数，否则两个参
数须为整数。

In [57]:
M = torch.randn(10, 3, 5)
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
torch.baddbmm(M, batch1, batch2).size()

torch.Size([10, 3, 5])

### torch.bmm
torch.bmm(batch1, batch2, out=None) → Tensor  
对存储在两个批 batch1 和 batch2 内的矩阵进行批矩阵乘操作。 batch1 和 batch2 都为包含相
同数量矩阵的3维张量。 如果 batch1 是形为$b \times n \times m$的张量， batch1 是形为$b \times m \times p$的张量，则 out 和 mat 的形状都是$n \times p$，即$res=(beta*M)+(alpha*sum(batch1_i@batch2_i,i=0,b))$  
对类型为 FloatTensor 或 DoubleTensor 的输入， alpha and beta 必须为实数，否则两个参数须为整数。

In [58]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
res = torch.bmm(batch1, batch2)
res.size()

torch.Size([10, 3, 5])

### torch.lu
torch.lu(A, pivot=True, get_infos=False, out=None) → Tensor, IntTensor  
返回一个元组，包含LU 分解和 pivots。

In [59]:
A = torch.randn(2, 3, 3)
A

tensor([[[ 0.0776,  0.0252,  0.9465],
         [ 0.5351,  0.9792,  0.6946],
         [ 0.1453, -0.2859, -0.3821]],

        [[-0.4581,  1.3442,  0.4680],
         [ 1.9161,  0.9292, -0.6237],
         [-0.2159, -1.0528,  1.3636]]])

In [60]:
A_LU, pivots = torch.lu(A)
A_LU

tensor([[[ 0.5351,  0.9792,  0.6946],
         [ 0.2715, -0.5518, -0.5708],
         [ 0.1451,  0.2117,  0.9666]],

        [[ 1.9161,  0.9292, -0.6237],
         [-0.2391,  1.5664,  0.3188],
         [-0.1127, -0.6053,  1.4863]]])

In [61]:
pivots

tensor([[2, 3, 3],
        [2, 2, 3]], dtype=torch.int32)

### torch.lu_solve
torch.lu_solve(b, LU_data, LU_pivots, out=None) -> Tensor  
返回线性方程组$Ax=b$的LU解。

In [62]:
A = torch.randn(2, 3, 3)
b = torch.randn(2, 3)
A_LU = torch.lu(A)
x = torch.lu_solve(b, *A_LU)
torch.norm(torch.bmm(A, x.unsqueeze(2)) - b.unsqueeze(2))

tensor(4.6290e-07)

### torch.dot
torch.dot(tensor1, tensor2) → float  
计算两个张量的点乘(内乘)，两个张量都为1-D 向量。

In [63]:
torch.dot(torch.Tensor([2, 3]), torch.Tensor([2, 1]))

tensor(7.)

### torch.eig
torch.eig(a, eigenvectors=False, out=None) -> (Tensor, Tensor)  
计算实方阵 a 的特征值和特征向量

### torch.gels
torch.gels(B, A, out=None) → Tensor  
对形如$m \times n$的满秩矩阵 a 计算其最小二乘和最小范数问题的解。 如果$m \geqslant n$ , gels 对最小二乘问题进行求解，即：$$\begin{array}{ll}
   \min_X & \|AX-B\|_2.
   \end{array}$$
如果$m<n$, gels 求解最小范数问题，即：$$ \begin{array}{ll}
   \min_X & \|X\|_2 & \text{subject to} & AX = B.
   \end{array}$$
返回矩阵X的前n 行包含解。余下的行包含以下残差信息: 相应列从第n 行开始计算的每列的欧式距离。  
注意： 返回矩阵总是被转置，无论输入矩阵的原始布局如何，总会被转置；即，总是有stride (1, m) 而不是 (m, 1).

In [64]:
A = torch.tensor([[1., 1, 1],
                  [2, 3, 4],
                  [3, 5, 2],
                  [4, 2, 5],
                  [5, 4, 3]])
B = torch.tensor([[-10., -3],
                  [ 12, 14],
                  [ 14, 12],
                  [ 16, 16],
                  [ 18, 16]])
X, _ = torch.gels(B, A)
X

tensor([[ 2.0000,  1.0000],
        [ 1.0000,  1.0000],
        [ 1.0000,  2.0000],
        [10.9635,  4.8501],
        [ 8.9332,  5.2418]])

### torch.ger
torch.ger(vec1, vec2, out=None) → Tensor  
计算两向量 vec1 , vec2 的张量积。如果 vec1 的长度为 n , vec2 长度为 m ，则输出 out 应为形如n x m的矩阵。

In [65]:
v1 = torch.arange(1, 5)
v2 = torch.arange(1, 4)
torch.ger(v1, v2)

tensor([[ 1,  2,  3],
        [ 2,  4,  6],
        [ 3,  6,  9],
        [ 4,  8, 12]])

### torch.solve
torch.solve(B, A, out=None) -> (Tensor, Tensor)  
返回线性方程组 AX = B 的解。  
LU 包含两个矩阵L，U。A须为非奇异方阵，如果A是一个$m \times m$ 矩阵，B 是$m \times k$矩阵，则LU 是 $m \times m$矩阵， X为$m \times k$矩阵。

In [66]:
A = torch.tensor([[ 6.80, -2.11,  5.66,  5.97,  8.23],
                  [-6.05, -3.30,  5.36, -4.44,  1.08],
                  [-0.45,  2.58, -2.70,  0.27,  9.04],
                  [ 8.32,  2.71,  4.35, -7.17,  2.14],
                  [-9.67, -5.14, -7.26,  6.08, -6.87]]).t()
B = torch.tensor([[ 4.02,  6.19, -8.22, -7.57, -3.03],
                  [-1.56,  4.00, -8.67,  1.75,  2.86],
                  [ 9.81, -4.09, -4.57, -8.61,  8.99]]).t()
X, LU = torch.solve(B, A)
torch.dist(B, torch.mm(A, X))

tensor(7.0977e-06)

In [67]:
A = torch.randn(2, 3, 1, 4, 4)
B = torch.randn(2, 3, 1, 4, 6)
X, LU = torch.solve(B, A)
torch.dist(B, A.matmul(X))

tensor(3.2262e-06)

### torch.inverse
torch.inverse(input, out=None) → Tensor  
对方阵输入 input 取逆。

In [68]:
x = torch.rand(4, 4)
y = torch.inverse(x)
z = torch.mm(x, y)
z

tensor([[ 1.0000e+00,  2.3842e-07, -5.5879e-08,  1.1921e-07],
        [ 0.0000e+00,  1.0000e+00, -5.2154e-08,  1.1921e-07],
        [ 4.7684e-07,  2.3842e-07,  1.0000e+00,  0.0000e+00],
        [ 4.7684e-07,  2.3842e-07, -1.1176e-07,  1.0000e+00]])

In [69]:
torch.max(torch.abs(z - torch.eye(4)))

tensor(4.7684e-07)

In [70]:
x = torch.randn(2, 3, 4, 4)
y = torch.inverse(x)
z = torch.matmul(x, y)
torch.max(torch.abs(z - torch.eye(4).expand_as(x)))

tensor(2.8610e-06)

### torch.mm
torch.mm(mat1, mat2, out=None) → Tensor  
对矩阵 mat1 和 mat2 进行相乘。 如果 mat1 是一个$n \times m$ 张量， mat2 是一个$m \times p$ 张量，将会输出一个$n \times p$张量 out 。

In [71]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.mm(mat1, mat2)

tensor([[ 1.8535, -1.2918, -3.9691],
        [-2.9728,  0.4596, -5.2783]])

### torch.mv
torch.mv(mat, vec, out=None) → Tensor  
对矩阵 mat 和向量 vec 进行相乘。 如果 mat 是一个$n \times m$ 张量， vec 是一个$m$元 1维张量，将会输出一个$n$元 1维张量。

In [72]:
mat = torch.randn(2, 3)
vec = torch.randn(3)
torch.mv(mat, vec)

tensor([ 0.4932, -0.2171])

### torch.qr
torch.qr(input, out=None) -> (Tensor, Tensor)  
计算输入矩阵的QR分解：返回两个矩阵$q,r$，使得$x=q*r$，这里$q$是一个半正交矩阵与$r$是一个上三角矩阵  
本函数返回一个thin(reduced)QR分解。

In [73]:
a = torch.tensor([[12., -51, 4], [6, 167, -68], [-4, 24, -41]])
q, r = torch.qr(a)
q

tensor([[-0.8571,  0.3943,  0.3314],
        [-0.4286, -0.9029, -0.0343],
        [ 0.2857, -0.1714,  0.9429]])

In [74]:
r

tensor([[ -14.0000,  -21.0000,   14.0000],
        [   0.0000, -175.0000,   70.0000],
        [   0.0000,    0.0000,  -35.0000]])

In [75]:
torch.mm(q, r).round()

tensor([[ 12., -51.,   4.],
        [  6., 167., -68.],
        [ -4.,  24., -41.]])

In [76]:
torch.mm(q.t(), q).round()

tensor([[1., 0., 0.],
        [0., 1., -0.],
        [0., -0., 1.]])

### torch.svd
torch.svd(input, some=True, out=None) -> (Tensor, Tensor, Tensor)  
返回对形如$n \times m$的实矩阵 A 进行奇异值分解的结果，使得$A = USV'*$。$U$形状为$n \times n$，$S$形状为$n \times m$，$V$形状为$m \times m$。

In [77]:
a = torch.tensor([[8.79,  6.11, -9.15,  9.57, -3.49,  9.84],
                  [9.93,  6.91, -7.93,  1.64,  4.02,  0.15],
                  [9.83,  5.04,  4.86,  8.83,  9.80, -8.99],
                  [5.45, -0.27,  4.85,  0.74, 10.00, -6.02],
                  [3.16,  7.98,  3.01,  5.80,  4.27, -5.31]]).t()
u, s, v = torch.svd(a)
u

tensor([[-0.5911,  0.2632,  0.3554,  0.3143,  0.2299],
        [-0.3976,  0.2438, -0.2224, -0.7535, -0.3636],
        [-0.0335, -0.6003, -0.4508,  0.2334, -0.3055],
        [-0.4297,  0.2362, -0.6859,  0.3319,  0.1649],
        [-0.4697, -0.3509,  0.3874,  0.1587, -0.5183],
        [ 0.2934,  0.5763, -0.0209,  0.3791, -0.6526]])

In [78]:
s

tensor([27.4687, 22.6432,  8.5584,  5.9857,  2.0149])

In [79]:
v

tensor([[-0.2514,  0.8148, -0.2606,  0.3967, -0.2180],
        [-0.3968,  0.3587,  0.7008, -0.4507,  0.1402],
        [-0.6922, -0.2489, -0.2208,  0.2513,  0.5891],
        [-0.3662, -0.3686,  0.3859,  0.4342, -0.6265],
        [-0.4076, -0.0980, -0.4933, -0.6227, -0.4396]])

In [80]:
torch.dist(a, torch.mm(torch.mm(u, torch.diag(s)), v.t()))

tensor(1.4596e-05)

### torch.symeig
torch.symeig(input, eigenvectors=False, upper=True, out=None) -> (Tensor, Tensor)  
返回实对称矩阵 input 的特征值和特征向量。

In [81]:
a = torch.tensor([[ 1.96,  0.00,  0.00,  0.00,  0.00],
                  [-6.49,  3.80,  0.00,  0.00,  0.00],
                  [-0.47, -6.39,  4.17,  0.00,  0.00],
                  [-7.20,  1.50, -1.51,  5.70,  0.00],
                  [-0.65, -6.34,  2.67,  1.80, -7.10]]).t()
e, v = torch.symeig(a, eigenvectors=True)
e

tensor([-11.0656,  -6.2287,   0.8640,   8.8655,  16.0948])

In [82]:
v

tensor([[-0.2981, -0.6075,  0.4026, -0.3745,  0.4896],
        [-0.5078, -0.2880, -0.4066, -0.3572, -0.6053],
        [-0.0816, -0.3843, -0.6600,  0.5008,  0.3991],
        [-0.0036, -0.4467,  0.4553,  0.6204, -0.4564],
        [-0.8041,  0.4480,  0.1725,  0.3108,  0.1622]])