In [1]:
import torch
import math

# 数学操作 Math operations

### torch.abs
torch.abs(input, out=None) → Tensor  
计算输入张量的每个元素绝对值

In [2]:
# 取绝对值
torch.abs(torch.FloatTensor([-1, -2, -3]))

tensor([1., 2., 3.])

### torch.acos
torch.acos(input, out=None) → Tensor  
返回一个新张量，包含输入张量每个元素的反余弦。 

In [3]:
a = torch.randn(4)
a

tensor([ 0.7032, -0.7961, -0.8925,  0.3463])

In [4]:
# 求反余弦
torch.acos(a)

tensor([0.7908, 2.4916, 2.6737, 1.2172])

### torch.add
torch.add(input, value, out=None)  
对输入张量 input 逐元素加上标量值 value ，并返回结果到一个新的张量 out ，即$out=tensor+value$。  
如果输入 input 是FloatTensor or DoubleTensor类型，则 value 必须为实数，否则须为整数。  
【译注：似乎并非如此，无关输入类型，value 取整数、实数皆可。】

In [5]:
a = torch.randn(4)
a

tensor([-0.5200,  0.4050,  0.4274, -1.1527])

In [6]:
# 加上20的标量值
torch.add(a, 20)

tensor([19.4800, 20.4050, 20.4274, 18.8473])

In [7]:
b = torch.randn(4, 1)
b

tensor([[-0.8184],
        [ 0.2628],
        [-0.8257],
        [-0.0470]])

In [8]:
# 求a + 10b
torch.add(a, 10, b)

tensor([[-8.7038, -7.7788, -7.7564, -9.3365],
        [ 2.1082,  3.0332,  3.0556,  1.4755],
        [-8.7770, -7.8520, -7.8296, -9.4097],
        [-0.9899, -0.0649, -0.0425, -1.6226]])

### torch.addcdiv
torch.addcdiv(tensor, value=1, tensor1, tensor2, out=None) → Tensor  
用 tensor2 对 tensor1 逐元素相除，然后乘以标量值 value 并加到 tensor 。  
张量的形状不需要匹配，但元素数量必须一致。  
如果输入是FloatTensor or DoubleTensor类型，则 value 必须为实数，否则须为整数。

In [9]:
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
# 求t + (t1/t2) * 0.1
torch.addcdiv(t, 0.1, t1, t2)

tensor([[-1.1297, -1.0286,  0.1527],
        [-1.1376, -1.0365,  0.1836],
        [-1.0154, -0.9147, -0.2905]])

### torch.addcmul
torch.addcmul(tensor, value=1, tensor1, tensor2, out=None) → Tensor  
用 tensor2 对 tensor1 逐元素相乘，并对结果乘以标量值 value 然后加到 tensor 。 张量的形状不需要匹配，但元素数量必须一致。 如果输入是FloatTensor or DoubleTensor类型，则 value必须为实数，否则须为整数。

In [10]:
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
# 求t + (t1*t2) * 0.1
torch.addcmul(t, 0.1, t1, t2)

tensor([[ 1.8053,  0.4219, -0.4325],
        [ 1.2761,  0.9093, -0.4943],
        [ 1.4720,  0.7289, -0.4714]])

### torch.asin
torch.asin(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的反正弦函数

In [11]:
a = torch.randn(4)
a

tensor([ 0.8525,  1.5362, -0.2964, -3.4188])

In [12]:
# 求反正弦
torch.asin(a)

tensor([ 1.0208,     nan, -0.3010,     nan])

### torch.atan
torch.atan(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的反正切函数

In [13]:
a = torch.randn(4)
a

tensor([-0.4156, -0.9798, -0.3482, -0.7737])

In [14]:
# 求反正切
torch.atan(a)

tensor([-0.3939, -0.7752, -0.3351, -0.6585])

### torch.atan2
torch.atan2(input1, input2, out=None) → Tensor  
返回一个新张量，包含两个输入张量 input1 和 input2 的反正切函数

In [15]:
a = torch.randn(4)
a

tensor([ 1.2957,  0.0048,  0.2600, -0.7211])

In [16]:
# 求反正切
torch.atan2(a, torch.randn(4))

tensor([ 2.6786,  3.1231,  2.6070, -2.5074])

### torch.ceil
torch.ceil(input, out=None) → Tensor  
向上取整函数，对输入 input 张量每个元素向上取整, 即取不小于每个元素的最小整数，并返回结果到输出。

In [17]:
a = torch.randn(4)
a

tensor([-1.2133, -0.5561,  0.1049, -0.8851])

In [18]:
# 向上取整
torch.ceil(a)

tensor([-1., -0.,  1., -0.])

### torch.clamp
torch.clamp(input, min, max, out=None) → Tensor  
将输入 input 张量每个元素的夹紧到区间 [min, max]，并返回结果到一个新张量。  
操作定义如下：
$$ y_i = \left\{ \begin{array}{111} 
        min & \textrm{if $x_i < min$} \\ 
        x_i & \textrm{if $ min \leqslant x_i \leqslant max$} \\ 
        max & \textrm{if $x_i > max$}  
\end{array} \right.$$
如果输入是FloatTensor or DoubleTensor类型，则参数 min max 必须为实数，否则须为整数。  
【译注：似乎并非如此，无关输入类型， min，max 取整数、实数皆可。】

In [19]:
a = torch.randn(4)
a

tensor([-0.3689,  0.2135, -1.3652,  0.3331])

In [20]:
torch.clamp(a, min=-0.5, max=0.5)

tensor([-0.3689,  0.2135, -0.5000,  0.3331])

In [21]:
torch.clamp(a, min=0.5)

tensor([0.5000, 0.5000, 0.5000, 0.5000])

In [22]:
torch.clamp(a, max=0.5)

tensor([-0.3689,  0.2135, -1.3652,  0.3331])

### torch.cos
torch.cos(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的余弦。

In [23]:
a = torch.randn(4)
a

tensor([-1.9117,  0.7407,  1.5308,  0.8977])

In [24]:
# 求余弦
torch.cos(a)

tensor([-0.3343,  0.7380,  0.0400,  0.6234])

### torch.cosh
torch.cosh(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的双曲余弦。

In [25]:
a = torch.randn(4)
a

tensor([-0.7729, -0.6909,  0.9149, -2.1728])

In [26]:
# 双曲余弦
torch.cosh(a)

tensor([1.3139, 1.2483, 1.4486, 4.4484])

### torch.div()  
torch.div(input, value, out=None)
将 input 逐元素除以标量值 value ，并返回结果到输出张量 out 。 即 out = tensor/value
如果输入是FloatTensor or DoubleTensor类型，则参数 value 必须为实数，否则须为整数。  
【译注：似乎并非如此，无关输入类型， value 取整数、实数皆可。】

In [27]:
a = torch.randn(5)
a

tensor([ 0.7201,  0.8582, -1.5971, -0.2867,  0.0020])

In [28]:
# 求a/0.5
torch.div(a, 0.5)

tensor([ 1.4403,  1.7163, -3.1942, -0.5735,  0.0040])

In [29]:
a = torch.randn(4, 4)
a

tensor([[ 0.0255,  0.4124, -1.3918, -1.2483],
        [ 0.0598,  1.3476,  0.8627,  1.7644],
        [ 1.3376, -1.9968, -0.8483, -1.6009],
        [ 0.6231, -0.1269, -0.4626, -0.3599]])

In [30]:
b = torch.randn(4)
b

tensor([ 1.0623, -0.7571, -0.6310, -1.2394])

In [31]:
torch.div(a, b)

tensor([[ 0.0240, -0.5447,  2.2058,  1.0072],
        [ 0.0563, -1.7800, -1.3673, -1.4236],
        [ 1.2591,  2.6375,  1.3444,  1.2917],
        [ 0.5866,  0.1677,  0.7332,  0.2904]])

### torch.exp
torch.exp(tensor, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的指数。

In [32]:
torch.exp(torch.Tensor([0, math.log(2)]))

tensor([1., 2.])

### torch.floor
torch.floor(input, out=None) → Tensor  
向下取整函数: 返回一个新张量，包含输入 input 张量每个元素的Øoor，即不小于元素的最大整数。

In [33]:
a = torch.randn(4)
a

tensor([-0.5539,  0.3833,  1.3713, -1.5952])

In [34]:
# 向下取整
torch.floor(a)

tensor([-1.,  0.,  1., -2.])

### torch.fmod
torch.fmod(input, divisor, out=None) → Tensor    
计算除法余数。 除数与被除数可能同时含有整数和浮点数。此时，余数的正负与被除数相同。

In [35]:
# 求余数
torch.fmod(torch.Tensor([-3, -2, -1, 1, 2, 3]), 2)

tensor([-1., -0., -1.,  1.,  0.,  1.])

In [36]:
torch.fmod(torch.Tensor([1, 2, 3, 4, 5]), 1.5)

tensor([1.0000, 0.5000, 0.0000, 1.0000, 0.5000])

### torch.frac
torch.frac(tensor, out=None) → Tensor  
返回每个元素的分数部分。

In [37]:
# 求分数部分
torch.frac(torch.Tensor([1, 2.5, -3.2]))

tensor([ 0.0000,  0.5000, -0.2000])

### torch.lerp
torch.lerp(start, end, weight, out=None)  
对两个张量以 start ， end 做线性插值， 将结果返回到输出张量。即$out_i=start_i+weight*(end_i - start_i)$

In [38]:
start = torch.arange(1., 5.)
end = torch.Tensor(4).fill_(10)
start

tensor([1., 2., 3., 4.])

In [39]:
end

tensor([10., 10., 10., 10.])

In [40]:
torch.lerp(start, end, 0.5)

tensor([5.5000, 6.0000, 6.5000, 7.0000])

### torch.log
torch.log(input, out=None) → Tensor  
计算 input 的自然对数

In [41]:
a = torch.randn(5)
a

tensor([-1.0179, -0.5865,  0.0515, -0.0925, -0.3776])

In [42]:
# 求自然对数
torch.log(a)

tensor([    nan,     nan, -2.9666,     nan,     nan])

### torch.log1p
torch.log1p(input, out=None) → Tensor  
计算$input+1$的自然对数$y_i=log(x_i+1)$  
注意：对值比较小的输入，此函数比 torch.log() 更准确。  
如果输入是FloatTensor or DoubleTensor类型，则 value 必须为实数，否则须为整数。

In [43]:
a = torch.randn(5)
a

tensor([ 0.1929,  0.8332,  1.0046, -1.2882,  2.6807])

In [44]:
torch.log1p(a)

tensor([0.1764, 0.6061, 0.6955,    nan, 1.3031])

### torch.mul
torch.mul(input, value, out=None)  
用标量值 value 乘以输入 input 的每个元素，并返回一个新的结果张量。  
$$out=tensor*value$$
如果输入是FloatTensor or DoubleTensor类型，则 value 必须为实数，否则须为整数。  
【译注：似乎并非如此，无关输入类型，value 取整数、实数皆可。】

In [45]:
a = torch.randn(3)
a

tensor([ 0.5308, -1.4645, -0.6628])

In [46]:
# 对应位相乘
torch.mul(a, 100)

tensor([  53.0791, -146.4534,  -66.2787])

In [47]:
a = torch.randn(1, 4)
a

tensor([[ 0.7659,  0.6304, -0.0618,  0.0389]])

In [48]:
b = torch.randn(4, 1)
b

tensor([[ 0.4791],
        [ 0.2403],
        [-1.2320],
        [ 0.5636]])

In [49]:
torch.mul(a, b)

tensor([[ 0.3670,  0.3021, -0.0296,  0.0187],
        [ 0.1841,  0.1515, -0.0148,  0.0094],
        [-0.9436, -0.7767,  0.0761, -0.0480],
        [ 0.4317,  0.3553, -0.0348,  0.0219]])

### torch.neg
torch.neg(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量按元素取负。 即$out=-1*input$

In [50]:
a = torch.randn(5)
a

tensor([ 1.6001, -1.4278,  0.2710, -0.9890, -0.8102])

In [51]:
# 取反
torch.neg(a)

tensor([-1.6001,  1.4278, -0.2710,  0.9890,  0.8102])

### torch.pow
torch.pow(input, exponent, out=None)  
对输入 input 的按元素求 exponent 次幂值，并返回结果张量。 幂值 exponent 可以为单一 float 数或者与 input 相同元素数的张量。
- 当幂值为标量时，执行操作：$out_i=x^{exponent}$
- 当幂值为张量时，执行操作：$out_i=x^{exponent_i}$

In [52]:
a = torch.randn(4)
a

tensor([ 1.7536, -1.5000, -1.4633,  0.4366])

In [53]:
torch.pow(a, 2)

tensor([3.0752, 2.2500, 2.1412, 0.1906])

In [54]:
exp = torch.arange(1, 5)
a = torch.arange(1, 5)
a

tensor([1, 2, 3, 4])

In [55]:
exp

tensor([1, 2, 3, 4])

In [56]:
torch.pow(a, exp)

tensor([  1,   4,  27, 256])

In [57]:
exp = torch.arange(1, 5)
base = 2
torch.pow(base, exp)

tensor([ 2,  4,  8, 16])

### torch.reciprocal
torch.reciprocal(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的倒数，即 1.0/x。

In [58]:
a = torch.randn(4)
a

tensor([ 0.6473,  1.6942, -0.5579, -1.8421])

In [59]:
# 求倒数
torch.reciprocal(a)

tensor([ 1.5449,  0.5902, -1.7925, -0.5429])

### torch.remainder
torch.remainder(input, divisor, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的除法余数。 除数与被除数可能同时包含整数或浮点数。余数与除数有相同的符号。

In [60]:
# 求余数
torch.remainder(torch.Tensor([-3, -2, -1, 1, 2, 3]), 2)

tensor([1., 0., 1., 1., 0., 1.])

In [61]:
torch.remainder(torch.Tensor([1, 2, 3, 4, 5]), 1.5)

tensor([1.0000, 0.5000, 0.0000, 1.0000, 0.5000])

### torch.round
torch.round(input, out=None) → Tensor  
返回一个新张量，将输入 input 张量每个元素舍入到最近的整数。

In [62]:
a = torch.randn(4)
a

tensor([-1.7783, -1.3024,  0.6761, -0.7430])

In [63]:
# 四舍五入
torch.round(a)

tensor([-2., -1.,  1., -1.])

### torch.rsqrt
torch.rsqrt(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的平方根倒数。

In [64]:
a = torch.randn(4)
a

tensor([2.2418, 0.0087, 0.2466, 1.1488])

In [65]:
#求平方根倒数
torch.rsqrt(a)

tensor([ 0.6679, 10.7480,  2.0136,  0.9330])

### torch.sigmoid
torch.sigmoid(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的sigmoid值。

In [66]:
a = torch.randn(4)
a

tensor([ 1.7111,  0.3512, -1.8445,  0.3662])

In [67]:
# 求sigmoid值
torch.sigmoid(a)

tensor([0.8470, 0.5869, 0.1365, 0.5905])

### torch.sign
torch.sign(input, out=None) → Tensor  
符号函数：返回一个新张量，包含输入 input 张量每个元素的正负。

In [68]:
a = torch.randn(4)
a

tensor([-0.0344, -0.2544,  0.2738, -0.6572])

In [69]:
# 求正负号
torch.sign(a)

tensor([-1., -1.,  1., -1.])

### torch.sin
torch.sin(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的正弦。

In [70]:
a = torch.randn(4)
a

tensor([-0.8777, -0.9739,  0.8721, -1.3474])

In [71]:
# 求正弦
torch.sin(a)

tensor([-0.7693, -0.8271,  0.7657, -0.9751])

### torch.sinh
torch.sinh(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的双曲正弦。

In [72]:
a = torch.randn(4)
a

tensor([-0.6671, -0.5111,  0.0366,  0.3153])

In [73]:
# 求双曲正弦
torch.sinh(a)

tensor([-0.7177, -0.5337,  0.0366,  0.3206])

### torch.sqrt
torch.sqrt(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的平方根。

In [74]:
a = torch.randn(4)
a

tensor([ 0.7595,  0.8463, -1.5662, -0.1815])

In [75]:
# 求平方根
torch.sqrt(a)

tensor([0.8715, 0.9199,    nan,    nan])

### torch.tan
torch.tan(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的正切。

In [76]:
a = torch.randn(4)
a

tensor([-0.8239, -0.3524,  0.2862,  0.1885])

In [77]:
# 求正弦
torch.tan(a)

tensor([-1.0802, -0.3678,  0.2943,  0.1907])

### torch.tanh
torch.tanh(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的双曲正切。

In [78]:
a = torch.randn(4)
a

tensor([-0.1773, -1.3162, -0.4035, -1.6975])

In [79]:
# 求双曲正切
torch.tanh(a)

tensor([-0.1755, -0.8658, -0.3830, -0.9351])

### torch.trunc
torch.trunc(input, out=None) → Tensor  
返回一个新张量，包含输入 input 张量每个元素的截断值(标量x的截断值是最接近其的整数，其比x更接近零。简而言之，有符号数的小数部分被舍弃)

In [80]:
a = torch.randn(4)
a

tensor([ 1.6792,  1.9038, -0.8709,  0.0381])

In [81]:
# 有符号数的小数部分被舍弃
torch.trunc(a)

tensor([1., 1., -0., 0.])

# Reduction Ops

### torch.cumprod
torch.cumprod(input, dim, out=None) → Tensor  
返回输入沿指定维度的累积积。例如，如果输入是一个N 元向量，则结果也是一个N 元向量，第 i 个输出元素值为$y_i=x_1*x_2*x_3* \dots * x_i$

In [82]:
a = torch.randn(10)
a

tensor([-0.6383, -0.2396,  0.2207,  0.3089, -1.3117, -0.1321, -0.7035,  0.9341,
        -0.9783, -1.4102])

In [83]:
# 累积积
torch.cumprod(a, dim=0)

tensor([-0.6383,  0.1529,  0.0338,  0.0104, -0.0137,  0.0018, -0.0013, -0.0012,
         0.0012, -0.0016])

In [84]:
a[5] = 0.0
torch.cumprod(a, dim=0)

tensor([-0.6383,  0.1529,  0.0338,  0.0104, -0.0137, -0.0000,  0.0000,  0.0000,
        -0.0000,  0.0000])

### torch.cumsum
torch.cumsum(input, dim, out=None) → Tensor  
返回输入沿指定维度的累积和。例如，如果输入是一个N元向量，则结果也是一个N元向量，第 i 个输出元素值为$y_i=x_1+x_2+x_3+ \dots + x_i$

In [85]:
a = torch.randn(10)
a

tensor([ 0.0058, -1.0902, -1.8804, -0.0825, -0.5588,  0.3222,  1.3519, -0.6160,
        -2.5255, -0.3036])

In [86]:
# 累积和
torch.cumsum(a, dim=0)

tensor([ 0.0058, -1.0845, -2.9648, -3.0474, -3.6062, -3.2840, -1.9321, -2.5481,
        -5.0736, -5.3771])

### torch.dist
torch.dist(input, other, p=2, out=None) → Tensor  
返回 ( input - other ) 的 p 范数。

In [87]:
x = torch.randn(4)
x

tensor([-0.5019,  1.6696,  0.3584, -0.3592])

In [88]:
y = torch.randn(4)
y

tensor([-0.2053, -1.5023, -0.6129, -0.4984])

In [89]:
# 求范数为3.5的距离
torch.dist(x, y, 3.5)

tensor(3.1865)

In [90]:
torch.dist(x, y ,3)

tensor(3.2030)

In [91]:
torch.dist(x, y, 0)

tensor(4.)

In [92]:
torch.dist(x, y, 1)

tensor(4.5792)

### torch.mean
torch.mean(input) → float  
返回输入张量所有元素的均值。

In [93]:
a = torch.randn(1, 3)
a

tensor([[-1.6522, -0.0695, -0.1107]])

In [94]:
# 求均值
torch.mean(a)

tensor(-0.6108)

In [95]:
a = torch.randn(4, 4)
a

tensor([[-0.1229,  0.4709,  0.4501,  0.1157],
        [ 0.8869, -0.0260, -0.3222,  0.4202],
        [-1.2305, -0.9898,  0.7677, -1.0830],
        [-1.3483, -0.5996,  1.7358, -0.3986]])

In [96]:
torch.mean(a, 1)

tensor([ 0.2285,  0.2397, -0.6339, -0.1527])

### torch.median
torch.median(input, dim=-1, values=None, indices=None) -> (Tensor, LongTensor)  
返回输入张量给定维度每行的中位数，同时返回一个包含中位数的索引的 LongTensor。  
dim 值默认为输入张量的最后一维。输出形状与输入相同，除了给定维度上为1。   
注意: 这个函数还没有在 torch.cuda.Tensor 中定义

In [97]:
a = torch.randn(4, 5)
a

tensor([[ 2.1408, -0.5851, -0.9250, -0.9860,  0.0418],
        [ 1.3958, -0.2554, -0.8721, -0.7919,  1.1196],
        [-0.1880,  0.0382,  0.3230,  1.2927,  0.3482],
        [ 0.3114,  1.7854,  0.8161,  1.8982,  1.0155]])

In [98]:
# 求每一列的中位数
torch.median(a, 1)

torch.return_types.median(
values=tensor([-0.5851, -0.2554,  0.3230,  1.0155]),
indices=tensor([1, 1, 2, 4]))

### torch.mode
torch.mode(input, dim=-1, values=None, indices=None) -> (Tensor, LongTensor)  
返回给定维 dim 上，每行的众数值。 同时返回一个 LongTensor ，包含众数值的索引。 dim 值默认为输入张量的最后一维。
输出形状与输入相同，除了给定维度上为1。  
注意: 这个函数还没有在 torch.cuda.Tensor 中定义

In [99]:
a = torch.randn(4, 5)
a

tensor([[ 0.4775,  0.8440,  0.6437, -0.6048,  1.4977],
        [-0.5245,  0.5440, -1.1884, -0.3609,  0.8270],
        [-0.3261, -1.6924,  1.1314,  2.8923, -0.1280],
        [-0.7832,  1.2341,  1.2226, -0.7511, -1.3697]])

In [100]:
torch.mode(a, 1)

torch.return_types.mode(
values=tensor([-0.6048, -1.1884, -1.6924, -1.3697]),
indices=tensor([3, 2, 1, 4]))

### torch.norm
torch.norm(input, p=2) → float  
返回输入张量 input 的p 范数。

In [101]:
a = torch.randn(1, 3)
a

tensor([[-0.3698, -0.4418,  0.6127]])

In [102]:
torch.norm(a, 3)

tensor(0.7158)

In [103]:
a = torch.randn(4, 2)
a

tensor([[ 0.1712,  0.9284],
        [-0.3784, -0.2970],
        [-0.7282,  1.7284],
        [ 1.3008, -1.5798]])

In [104]:
torch.norm(a, 2, 1)

tensor([0.9441, 0.4811, 1.8755, 2.0464])

In [105]:
torch.norm(a, 0, 1)

tensor([2., 2., 2., 2.])

### torch.prod
torch.prod(input) → float  
返回输入张量 input 所有元素的积。

In [106]:
a = torch.randn(1, 3)
a

tensor([[-2.0770,  0.7237, -0.9291]])

In [107]:
# 所有元素的积
torch.prod(a)

tensor(1.3965)

In [108]:
a = torch.randn(4, 2)
a

tensor([[ 0.2866,  0.4081],
        [ 0.6971, -1.3522],
        [ 0.0385, -0.4141],
        [-0.6735,  0.3267]])

In [109]:
torch.prod(a, 1)

tensor([ 0.1169, -0.9426, -0.0159, -0.2201])

### torch.std
torch.std(input) → float  
返回输入张量 input 所有元素的标准差。

In [110]:
a = torch.randn(1, 3)
a

tensor([[ 1.2462,  0.1795, -0.4397]])

In [111]:
# 标准差
torch.std(a)

tensor(0.8528)

In [112]:
a = torch.randn(4, 4)
a

tensor([[-0.6016, -0.4789,  0.9654, -0.2904],
        [-1.1243, -1.1415, -1.4875, -0.6266],
        [ 0.7495,  1.3934, -0.4393, -0.1371],
        [-0.6453,  0.2536,  0.6015,  0.4028]])

In [113]:
torch.std(a, dim=1)

tensor([0.7226, 0.3542, 0.8370, 0.5511])

### torch.sum
torch.sum(input) → float  
返回输入张量 input 所有元素的和

In [114]:
a = torch.randn(1, 3)
a

tensor([[ 0.9349, -0.1123,  0.1591]])

In [115]:
# 求和
torch.sum(a)

tensor(0.9816)

In [116]:
a = torch.randn(4, 4)
a

tensor([[-1.4759,  0.3958,  0.9018,  0.0825],
        [-0.8901, -1.8906,  2.0301,  2.0935],
        [ 0.7284,  0.3320,  0.3510,  0.3573],
        [-0.7475, -0.7327, -0.4361, -1.5005]])

In [117]:
# 按行求和
torch.sum(a, 1)

tensor([-0.0958,  1.3429,  1.7687, -3.4169])

### torch.var
torch.var(input) → float  
返回输入张量所有元素的方差  
输出形状与输入相同，除了给定维度上为1。

In [118]:
a = torch.randn(1, 3)
a

tensor([[-1.4907, -0.9399, -1.0295]])

In [119]:
# 方差
torch.var(a)

tensor(0.0874)

In [120]:
a = torch.randn(4, 4)
a

tensor([[ 1.8271, -0.2964,  2.2185,  1.8414],
        [ 1.7441, -1.5256, -0.5301,  0.5621],
        [ 0.6072,  0.0763,  0.5420,  1.0399],
        [-1.1358, -0.2698,  0.3132, -0.9402]])

In [121]:
# 按行求方差
torch.var(a, 1)

tensor([1.3083, 1.9835, 0.1556, 0.4374])

# 比较操作 Comparison Ops

### torch.eq
torch.eq(input, other, out=None) → Tensor  
比较元素相等性。第二个参数可为一个数或与第一个参数同类型形状的张量。

In [122]:
torch.eq(torch.Tensor([[1, 2], [3, 4]]), torch.Tensor([[1, 1], [4, 4]]))

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

### torch.equal
torch.equal(tensor1, tensor2) → bool  
如果两个张量有相同的形状和元素值，则返回 True ，否则 False 。

In [123]:
torch.equal(torch.Tensor([1, 2]), torch.Tensor([1, 2]))

True